# Generated by Django 3.2 on 2022-07-26 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheese',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product')),
                ('cheese_type', models.CharField(max_length=20)),
                ('milk', models.CharField(blank=True, max_length=20, null=True)),
                ('region', models.CharField(blank=True, max_length=20, null=True)),
                ('rennet', models.CharField(blank=True, max_length=20, null=True)),
                ('maker', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
