# Generated by Django 3.2 on 2022-07-29 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_wine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.product')),
                ('product1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product1', to='products.product')),
                ('product2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product2', to='products.product')),
            ],
        ),
    ]
